<?php
	if (array_key_exists('messageAlt',$this))
	{
		echo '<div style="float:center;  text-align:left; padding:20px; margin:25px">
			<h2>Message: </h2>
			<p>' . $this->message . '</p>
			</div>';
	}

	if (array_key_exists('message',$this))
	{
		echo '<div style="float:center;  width:50%;text-align:left; padding:20px; margin:25px">
			<h2>Statistik: </h2>
			<table>';
			foreach($this->message as $title => $stat)
			{
				echo '<tr>'.
						'<td><b>' . $title . ': </b></td>'.
						'<td >' . $stat . ' </td>'.
						'</tr>';
			}
			echo '</table>';
			
	}