<html>
	<head>
	</head>
	<body>
		<h1><p align="center"><font color="008800">Wissenschaftsbeziehungen im 19. Jahrhundert zwischen Deutschland und Russland auf den Gebieten Chemie, Pharmazie und Medizin</font></p></h2>
		
	
	
	
	
		<div style="height=112px width=274;float:right;padding:5px;"><img src="http://666kb.com/i/cd2wprm9mouia6vp5.jpg" alt="Russische Akademie der Wissenschaften zu St. Petersburg und Kunstkammer" /></div>
		<div>
			<p align="justify">Das seit Mai 2007 bestehende Vorhaben hat Dokumentation und Darstellung der wissenschaftlichen Beziehungen zwischen den deutschsprachigen Ländern und dem Russischen Reich auf den Gebieten Chemie, Pharmazie und Medizin im „langen“ 19. Jahrhundert zum Ziel. Russland bot vielen deutschen Medizinern und Naturwissenschaftlern Arbeits-, Forschungs- und Karrieremöglichkeiten, die sie in der Heimat nicht finden konnten. Umgekehrt besuchten russische Studenten, Akademiker und Wissenschaftler ausländische Universitäten, brachten von dort Eindrücke und Anregungen mit und publizierten wiederum u. a. auf Deutsch. Ein biobibliographisches Lexikon erfasst diejenigen Chemiker, Pharmazeuten und Mediziner, die bei diesen Kontakten eine wichtige Rolle spielten.</p>
			<p align="justify">Der Wissenschaftsaustausch wird zunächst anhand ausgewählter Disziplinen analysiert, bei denen sich in diesem Zeitraum ein Paradigmenwechsel im Sinne der naturwissenschaftlichen Grundlegung vollzog. Das Projekt sichert und erzeugt darüber hinaus jedoch auch ideen-, sozial- und kulturgeschichtliches Wissen. Die Ergebnisse sollen abschließend zu einem Gesamtbild mit Handbuchcharakter vereinigt werden. Historische Fundierung und Dekonstruktion nationaler Legendenbildung können sogar zu einer Förderung der aktuellen Wissenschaftsbeziehungen zwischen Deutschland und Russland beitragen.</p>
			<p align="justify">Für die laufende Veröffentlichung der Projektarbeit wurde die Schriftenreihe <em>Relationes</em> gegründet. 2008 ist der erste Band mit einer Edition von Quellen zu dem in St. Petersburg tätigen deutschen Chemiker und Pharmazeuten Carl Julius Fritzsche (1808–1871) und einer diskursanalytischen Untersuchung der populärphilosophischen Schriften des russischen Medizin-Nobelpreisträgers Il’ja Il’ič Mečnikov (1845–1916) erschienen. Im Jahr 2009 entstanden die beiden Monographien&nbsp;<em>Baltische Genesis. Die Grundlegung der Embryologie im 19. Jahrhundert </em>und<em> Lebensvorgänge. Deutsch-russische Wechselbeziehungen in der Physiologie des 19. Jahrhunderts.</em></p>
			<p align="justify">2010 wurden unter dem Titel <em>Russische Karrieren</em> die Biobibliographien der deutschen und russischen Leibärzte im Zarenreich vorgelegt.</p>
			<p align="justify">Im Jahr 2011 sind drei weitere Bände erschienen: die Monographie „Das allgemeinste Gesetz“. Karl Ernst von Baer (1792–1876) und die großen Diskurse des 19. Jahrhunderts von Ortrun Riha und Thomas Schmuck, der Tagungsband „Naturwissenschaft als Kommunikationsraum“. Internationale Tagung, Leipzig 29.9.–1.10.2010, herausgegeben von Ortrun Riha und Marta Fischer, und der Band zur bilateralen Forschungsentwicklung in Physiologischer Chemie „Lebendige Stoffe. Deutsch-russischer Wissensaustausch in der Physiologischen Chemie im 19. Jahrhundert“ von Regine Pfrepper.</p>
			<p align="justify">2012 wurden eine Dokumentation zur Pharmakologie, ein biobibliographisches Lexikon der Physiologen, eine kommentierte Briefedition sowie eine kommentierte Übersetzung von Reiseberichten russischer Physiologen, Biochemiker und Pharmakologen herausgebracht.</p>
	</body>
</html>




