
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
<title><?php echo $this->MNamestring; ?></title>

<meta name="description" content="<?php echo $this->Lstring; ?> <?php echo $this->MNamestring; ?> <?php echo $this->Bstring ?>, <?php echo $this->Dstring ?>">

<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">


        <style type="text/css">

                 .t100g {width:100%; vertical-align:top; text-align:left; font-weight:bold; color: #339966;}
                 .t100s {width:100%; vertical-align:top; text-align:left; font-weight:bold; color: #110408;}
                 .t100n {width:100%; vertical-align:top; text-align:left; font-weight:normal; color: #110408;}
                 .t10 {width:10%; vertical-align:bottom; font-weight:bold; color: #339966;}

                .t90l {width:90%; text-align: left; vertical-align:top; color: #339966;}
                 .t5s {width:5%; text-align:left; vertical-align:top; font-weight: bold; color: #110408;}
                .t95ls {width:95%; text-align:left; vertical-align:top; color: #110408;}
                .t95lk {width:95%; text-align:left; vertical-align:middle; font-weight:normal; font-size:smaller; color: #110408;}
                .t95lg {width:95%; text-align:left; vertical-align:top; font-weight:bold; color: #339966;}
                .t90r {width:90%; text-align:right; vertical-align:top; font-weight:bold; color: #339966;}


                .inhalt { font-family: "Arial Narrow"; text-align:center;}
                .fett { font-weight: bold; }
                .gruen { color: #339966; }
                .grau  { color: #110408; }

</style>
</head>


<body link="#339966" alink="#339966" vlink="#339966">

<div class="inhalt">



<table align="center" width="90%" border="0" cellpadding="0" cellspacing="2">

<tr>
  <td class="t10">&nbsp;</td>
  <td class="t90r"><a href="personendatenbank.html">zur&uuml;ck&nbsp;<img src="pfeil.jpg" border="0" width="40" height="19" title="zur&uuml;ck" alt="zur&uuml;ck"></a></td>
</tr>
</table>



   <table align="center" width="90%" border="0" cellpadding="0" cellspacing="2">

<tr>
   <td class="t100g"><h3><?php echo $this->MNamestring; ?></h3></td>
</tr>

<tr>
   <td class="t100s"><?php echo $this->ANamestring; ?></td>
</tr>

<tr>
   <td class="t100n">Namensvariationen: <?php echo $this->VNamestring; ?></td>
</tr>

<tr>
   <td class="t100n"><img src="<?php echo $this->Bildstring; ?>" height="150"></td>
</tr>


<tr>
   <td class="t100n">&nbsp;</td>
</tr>

<tr>
   <td class="t100n"><?php echo $this->Bstring ?>
</td>
</tr>

<tr>
   <td class="t100n"><?php echo $this->Dstring ?></td>
</tr>

<tr>
   <td class="t100n"><?php echo $this->Lstring; ?></td>
</tr>

</table>

&nbsp;

<table align="center" width="90%" border="0" cellpadding="0" cellspacing="2">

<tr>
	 <td class="t5s">V</td>
   <td class="t95lk"><?php echo $this->Fatherstring; ?></td>
</tr>

<tr>
   <td class="t5s">M</td>
   <td class="t95lk"><?php echo $this->Motherstring; ?></td>
</tr>

<tr>
   <td class="t5s">E</td>
   <td class="t95lk"><?php echo $this->MPstring; ?></td>
</tr>

<tr>
   <td class="t5s">G</td>
   <td class="t95lk"><?php echo $this->Sibstring; ?></td>
</tr>

<tr>
   <td class="t5s">N</td>
   <td class="t95lk"><?php echo $this->Descstring; ?></td>
</tr>

<tr>
   <td class="t5s">&nbsp;</td>
   <td class="t95lk">&nbsp;</td>
</tr>

<tr>
   <td class="t5s">A</td>
   <td class="t95ls"><?php echo $this-> Estring; ?></td>
</tr>

<tr>
   <td class="t5s">B</td>
   <td class="t95ls"><?php echo $this-> SOLstring; ?><b><?php echo $this->EuA; ?></b><br><?php echo $this->HAAstring; ?></td>
</tr>

<tr>
   <td class="t5s">WL</td>
   <td class="t95ls"><?php echo $this-> WLstring; ?></td>
</tr>

<tr>
   <td class="t5s">&nbsp;</td>
   <td class="t95lk">&nbsp;</td>
</tr>

<tr>
   <td class="t5s">M</td>
   <td class="t95lk"><?php echo $this-> MGstring; ?></td>
</tr>

<tr>
   <td class="t5s">GPV</td>
   <td class="t95lk"><?php echo $this-> GPVstring; ?></td>
</tr>


<tr>
   <td class="t5s">W</td>
   <td class="t95lk"><?php echo $this-> Wstring; ?>
</td>
</tr>

<tr>
   <td class="t5s">Q</td>
   <td class="t95lk"><?php echo $this-> Sstring; ?>
</td>
 </tr>

<tr>
   <td class="t5s">SL</td>
   <td class="t95lk">
<?php echo $this-> SLstring; ?>
</td>
 </tr>

<tr>
   <td class="t5s">P</td>
   <td class="t95lk">
<?php echo $this-> Pstring; ?>
</td>
 </tr>
 
  <tr>
   <td class="t5s">Kommentare</td>
   <td class="t95lk">
<?php echo $this-> Cstring; ?>
</td>
 </tr>

 
</table>
&nbsp;
<br>&nbsp;
<table align="center" width="90%" border="0" cellpadding="0" cellspacing="2">
<tr>
  <td class="t95lk">Empfohlene Zitierweise:
</td>
 </tr>
</table>



<table align="center" width="90%" border="0" cellpadding="0" cellspacing="2">
<tr>
  <td class="t100g">Fischer, Marta:  <?php echo $this->MNamestring; ?>. In: Personendatenbank zum Vorhaben "Wissenschaftsbeziehungen im 19. Jahrhundert zwischen Deutschland und Russland auf den Gebieten Chemie, Pharmazie und Medizin" bei der S&auml;chsischen Akademie der Wissenschaften zu Leipzig. Online-Ausgabe: <i>http://drw.saw-leipzig.de/<?php echo $this-> IDstring; ?>.html</i> (2. Mai 2012).
</td>
 </tr>
</table>


</div>
</body>

</html>
